--inserindo valores para pegar nome e sobrenome
DECLARE
  ID_CLIENTE_ENT NUMBER;
  NOME_COMPLETO VARCHAR2(200);
BEGIN
  ID_CLIENTE_ENT := 2;

  NOME_CLIENTE_ID(
    ID_CLIENTE_ENT => ID_CLIENTE_ENT,
    NOME_COMPLETO => NOME_COMPLETO
  );

DBMS_OUTPUT.PUT_LINE('NOME_COMPLETO = ' || NOME_COMPLETO);

  :NOME_COMPLETO := NOME_COMPLETO;
--rollback; 
END;